#!/usr/bin/env bash
# debug nginx port 80
# Fixes nginx listening port and reloads nginx master process.

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
