#!/usr/bin/env bash
# Dose following:
# Create file /var/run/myscript.pid containing script PID.
# Display To infinity and beyond indefiniy.
# Display "I hate the kill command" once receiving SIGTERM.
# Display "Y U no love me?!" once receive SIGINT.
# Delete file /var/run/myscript.pid and terminate once.
# receiving  SIGQUIT or SIGTERM.

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && rm /var/run/myscript.pid && exit' SIGTERM
	trap 'rm /var/run/myscript.pid && exit' SIGQUITgit 
done
