#!/usr/bin/env bash
#script uses while loop to display Best School ten times, On 9th displays Hi
n=0

while [ $n -lt 10 ]
do
	if [ $n -eq 8 ]
	then
		echo "Hi"
	fi
		echo "Best School"
		(( n++ ))
done
