#!/usr/bin/env bash
#script uses while loop to display Best School ten times, On 9th displays Hi

n=0

while [ $n -le 9 ]
do
	echo "Best School"
	n=$((n+1))
	if [ $n -eq 8 ]
	then
		echo "Hi"
	fi
done
