#!/usr/bin/env bash
# script uses while loop to display Best School, bad luck, good luck
n=1

while [ $n -lt 10 ]
do
	if [ $n -eq 4 ]
	then
		echo "bad luck"
	elif [ $n -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	n=$(( n+1 ))
done
